-- ⚠️ FINAL RESET: STRICT ER DIAGRAM MATCH (snake_case) ⚠️

-- 1. DROP Tables (Clean Slate - Both Snake and Pascal Case)
DROP TABLE IF EXISTS "Reservations" CASCADE;
DROP TABLE IF EXISTS "Product_categories" CASCADE;
DROP TABLE IF EXISTS "Products" CASCADE;
DROP TABLE IF EXISTS "Cabins" CASCADE;
DROP TABLE IF EXISTS "Categories" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Shops" CASCADE;

DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS product_categories CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS cabins CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS shops CASCADE;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CREATE Tables (Exact Match to Diagram)

-- shops
CREATE TABLE shops (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    location TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- users
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    measurements TEXT,
    style_preferences TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- categories
CREATE TABLE categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

-- products
CREATE TABLE products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT REFERENCES shops(id),
    name TEXT NOT NULL,
    size TEXT,
    color TEXT,
    stock INT DEFAULT 0,
    price NUMERIC(10, 2) NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- product_categories (Link Table)
CREATE TABLE product_categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT REFERENCES products(id),
    category_id BIGINT REFERENCES categories(id)
);

-- cabins
CREATE TABLE cabins (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    shop_id BIGINT REFERENCES shops(id),
    cabin_number INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- reservations
CREATE TABLE reservations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES users(id),
    product_id BIGINT REFERENCES products(id),
    cabin_id BIGINT REFERENCES cabins(id),
    date DATE NOT NULL,
    hour TIME NOT NULL,
    access_code TEXT,
    duration INT DEFAULT 30,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- 3. DISABLE RLS (Critical for Connection)
ALTER TABLE shops DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE cabins DISABLE ROW LEVEL SECURITY;
ALTER TABLE reservations DISABLE ROW LEVEL SECURITY;


-- 4. SEED DATA

INSERT INTO shops (name, location) VALUES 
('Fashion Avenue', 'Istinye Park AVM'),
('Urban Style', 'Kanyon AVM'),
('Vintage Corner', 'Kadikoy Moda');

INSERT INTO categories (name) VALUES 
('Elbiseler'), ('Takım Elbiseler'), ('Spor Giyim'), ('Aksesuarlar'), ('Ayakkabı');

-- Products (with images)
INSERT INTO products (shop_id, name, size, color, stock, price, image_url) VALUES 
-- Fashion Avenue
(1, 'Yazlık Çiçekli Elbise', 'M', 'Kırmızı', 15, 850.00, 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=400&auto=format&fit=crop'),
(1, 'Siyah Gece Elbisesi', 'S', 'Siyah', 8, 1200.00, 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?q=80&w=400&auto=format&fit=crop'),
(1, 'İpek Gömlek', 'L', 'Beyaz', 20, 950.00, 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?q=80&w=400&auto=format&fit=crop'),

-- Urban Style
(2, 'Slim Fit Lacivert Takım', '50', 'Lacivert', 5, 4500.00, 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=400&auto=format&fit=crop'),
(2, 'Gri Blazer Ceket', '48', 'Gri', 10, 2200.00, 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=400&auto=format&fit=crop'),
(2, 'Deri Ceket', 'M', 'Siyah', 7, 3500.00, 'https://images.unsplash.com/photo-1551028919-ac66e6a39d44?q=80&w=400&auto=format&fit=crop'),

-- Vintage Corner
(3, 'Retro Kot Ceket', 'L', 'Mavi', 12, 1100.00, 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?q=80&w=400&auto=format&fit=crop'),
(3, 'Desenli Vintage Gömlek', 'M', 'Çok Renkli', 15, 600.00, 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=400&auto=format&fit=crop'),
(3, 'Kanvas Pantolon', '32', 'Bej', 25, 750.00, 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=400&auto=format&fit=crop'),
(3, 'Spor Ayakkabı', '42', 'Beyaz', 10, 1800.00, 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?q=80&w=400&auto=format&fit=crop');

-- Cabins
INSERT INTO cabins (shop_id, cabin_number) VALUES 
(1, 1), (1, 2), (1, 3),
(2, 1), (2, 2),
(3, 1);

-- Join Table (Product Categories)
INSERT INTO product_categories (product_id, category_id) VALUES 
(1, 1), -- Yazlık Elbise -> Elbiseler
(2, 1), -- Gece Elbisesi -> Elbiseler
(2, 4), -- Gece Elbisesi -> Aksesuarlar (Örnek)
(3, 3), -- Gömlek -> Spor/Casual?
(4, 2), -- Takım -> Takım
(5, 2), -- Blazer -> Takım
(6, 3), -- Deri Ceket -> Spor
(7, 3), -- Kot Ceket -> Spor
(9, 3), -- Pantolon -> Spor
(10, 5); -- Ayakkabı -> Ayakkabı

-- Users
INSERT INTO users (id, name, email) VALUES 
('00000000-0000-0000-0000-000000000001', 'Ahmet Yılmaz', 'ahmet@ornek.com'),
('00000000-0000-0000-0000-000000000002', 'Ayşe Demir', 'ayse@ornek.com');
